# wget 'https://xaemiphor.github.io/homelab/compose/autoheal.yml' -O /srv/compose/autoheal.yml
services:
  autoheal:
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    image: willfarrell/autoheal
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
